import type {
  CardModel,
  PlayerModel,
  ScreenAction,
  ScreenId,
  ScreenModel,
  ScreenRow,
  Tone,
} from "../../src/ui/model";

export type VisualPreviewFamily =
  | "brand"
  | "room-entry"
  | "lobby"
  | "table"
  | "choice"
  | "outcome"
  | "editorial"
  | "utility";

export const SCREEN_ORDER = Object.freeze([
  "login",
  "home",
  "play-mode",
  "create",
  "join",
  "lobby-host",
  "lobby-member",
  "game",
  "other-turn",
  "attack",
  "response",
  "favor",
  "give-card",
  "future",
  "explosion",
  "defuse",
  "eliminated",
  "result",
  "tutorial",
  "rules",
  "card-detail",
  "history",
  "game-menu",
  "network",
  "settings",
] as const satisfies readonly ScreenId[]);

const nav = (
  id: string,
  label: string,
  next: ScreenId,
  tone: Tone = "cream",
): ScreenAction => ({ id, label, next, tone, ...(id === "back" ? { back: true } : {}) });

const intent = (
  id: string,
  label: string,
  type: string,
  tone: Tone = "yellow",
  payload: Readonly<Record<string, unknown>> = {},
): ScreenAction => ({ id, label, tone, intent: { type, ...payload } });

const card = (
  token: string,
  type: CardModel["type"],
  name: string,
  image: string,
  singlePlayable: boolean,
): CardModel => ({ token, type, name, image, playable: singlePlayable, singlePlayable });

const CARDS = Object.freeze({
  attack: card("attack-01", "ATTACK", "攻击", "assets/cards/attack.png", true),
  skip: card("skip-01", "SKIP", "跳过", "assets/cards/skip.png", true),
  defuse: card("defuse-01", "DEFUSE", "拆弹", "assets/cards/defuse.png", false),
  shuffle: card("shuffle-01", "SHUFFLE", "洗牌", "assets/cards/shuffle.png", true),
  future: card("future-01", "SEE_FUTURE", "预见未来", "assets/cards/peek.png", true),
  favor: card("favor-01", "FAVOR", "帮忙", "assets/cards/reverse.png", true),
  nope: card("nope-01", "NOPE", "否决", "assets/cards/card-back.png", false),
  taco: card("taco-01", "CAT_TACO", "卷饼猫", "assets/cards/reverse.png", false),
  beard: card("beard-01", "CAT_BEARD", "胡须猫", "assets/cards/reverse.png", false),
});

const PLAYERS = Object.freeze([
  {
    id: "viewer",
    name: "蓝耳队长",
    avatar: "assets/cats/player.png",
    handCount: 6,
    alive: true,
    ready: true,
    bot: false,
    host: true,
    connected: true,
  },
  {
    id: "orange",
    name: "阿橘",
    avatar: "assets/cats/a-ju.png",
    handCount: 5,
    alive: true,
    ready: true,
    bot: false,
    host: false,
    connected: true,
  },
  {
    id: "gray",
    name: "小灰",
    avatar: "assets/cats/xiao-hui.png",
    handCount: 7,
    alive: true,
    ready: true,
    bot: false,
    host: false,
    connected: true,
  },
  {
    id: "white",
    name: "团子",
    avatar: "assets/cats/tuan-zi.png",
    handCount: 4,
    alive: true,
    ready: true,
    bot: true,
    host: false,
    connected: true,
  },
] satisfies readonly PlayerModel[]);

const HAND = Object.freeze([
  CARDS.attack,
  CARDS.skip,
  CARDS.defuse,
  CARDS.shuffle,
  CARDS.future,
  CARDS.favor,
] satisfies readonly CardModel[]);

const TABLE_BASE = Object.freeze({
  turn: 8,
  direction: "顺时针",
  deckCount: 18,
  discard: CARDS.defuse,
  hand: HAND,
  players: PLAYERS,
  myTurn: true,
  turnsOwed: 1,
} satisfies NonNullable<ScreenModel["table"]>);

const LOBBY_HOST_ROWS = Object.freeze([
  {
    id: "viewer",
    title: "你 · 房主",
    detail: "已准备",
    image: "assets/cats/player.png",
  },
  {
    id: "orange",
    title: "阿橘",
    detail: "已准备",
    image: "assets/cats/a-ju.png",
  },
  {
    id: "gray",
    title: "小灰",
    detail: "已准备",
    image: "assets/cats/xiao-hui.png",
  },
  {
    id: "invite",
    title: "邀请好友",
    detail: "还差 1 人",
    action: intent("share-empty-seat", "邀请好友", "ShareRoom", "cream"),
  },
] satisfies readonly ScreenRow[]);

const LOBBY_MEMBER_ROWS = Object.freeze([
  {
    id: "viewer",
    title: "你",
    detail: "已准备",
    image: "assets/cats/player.png",
  },
  {
    id: "orange",
    title: "阿橘 · 房主",
    detail: "已准备",
    image: "assets/cats/a-ju.png",
  },
  {
    id: "gray",
    title: "小灰",
    detail: "已准备",
    image: "assets/cats/xiao-hui.png",
  },
  {
    id: "white",
    title: "团子",
    detail: "已准备",
    image: "assets/cats/tuan-zi.png",
  },
] satisfies readonly ScreenRow[]);

const RULE_ROWS: readonly ScreenRow[] = Object.freeze([
  { id: "flow", title: "回合流程", detail: "先打任意张牌（也可不打），最后抽 1 张并结束当前欠回合。", action: nav("card-flow", "详情", "card-detail") },
  { id: "danger", title: "危险猫 × 4", detail: "抽到后立刻处理：拆弹，或者淘汰。", image: "assets/cards/danger.png", action: nav("card-danger", "详情", "card-detail") },
  { id: "defuse", title: "拆弹 × 6", detail: "化解危险，并秘密放回牌堆。", image: "assets/cards/defuse.png", action: nav("card-defuse", "详情", "card-detail") },
  { id: "nope", title: "否决 × 5", detail: "取消上一张可否决的动作牌。", image: "assets/cards/card-back.png", action: nav("card-nope", "详情", "card-detail") },
  { id: "attack", title: "攻击 × 4", detail: "结束回合，让下一位承担两个回合。", image: "assets/cards/attack.png", action: nav("card-attack", "详情", "card-detail") },
  { id: "favor", title: "帮忙 × 4", detail: "指定玩家秘密交给你一张手牌。", image: "assets/cards/reverse.png", action: nav("card-favor", "详情", "card-detail") },
  { id: "shuffle", title: "洗牌 × 4", detail: "立刻打乱抽牌堆。", image: "assets/cards/shuffle.png", action: nav("card-shuffle", "详情", "card-detail") },
  { id: "skip", title: "跳过 × 4", detail: "不抽牌，完成一个欠回合。", image: "assets/cards/skip.png", action: nav("card-skip", "详情", "card-detail") },
  { id: "future", title: "预见未来 × 5", detail: "秘密查看牌堆顶部三张牌。", image: "assets/cards/peek.png", action: nav("card-future", "详情", "card-detail") },
  { id: "cats", title: "猫咪牌 × 20", detail: "5 种图案各 4 张；单张无效果，同名牌可组成组合技。", image: "assets/cards/reverse.png", action: nav("card-cats", "详情", "card-detail") },
  { id: "combos", title: "两张 / 三张组合", detail: "两张同名随机偷 1 张；三张同名可声明牌型，命中才获得。", action: nav("card-combos", "详情", "card-detail") },
  { id: "platform", title: "数字平台规则", detail: "点击查看否决窗口、目标限制、超时和并发裁决。", action: nav("card-platform", "详情", "card-detail") },
]);

export const SCREEN_FIXTURES = Object.freeze({
  login: {
    id: "login",
    eyebrow: "原创回合制卡牌游戏",
    title: "炸毛危机",
    subtitle: "今晚谁先炸？",
    heroImage: "assets/cat-cast.png",
    heroLabel: "BOOM!",
    actions: [intent("login", "微信一键进入", "Login")],
  },
  home: {
    id: "home",
    eyebrow: "危险！毛茸茸！还会炸！",
    title: "炸毛危机",
    subtitle: "嗨，蓝耳队长",
    heroImage: "assets/cats/player.png",
    heroLabel: "BOOM!",
    rows: [{ id: "settings", title: "声音与振动", detail: "调整当前设备设置", action: nav("settings", "打开", "settings") }],
    actions: [
      nav("play", "开一局", "play-mode", "yellow"),
      nav("join", "加入房间", "join"),
      nav("tutorial", "新手教学", "tutorial", "cyan"),
      nav("rules", "规则图鉴", "rules"),
    ],
  },
  "play-mode": {
    id: "play-mode",
    eyebrow: "选择你的混乱方式",
    title: "开一局",
    heroImage: "assets/cats/player.png",
    rows: [
      { id: "create", title: "创建房间", detail: "设置人数与节奏，邀请好友", action: nav("create", "创建", "create") },
      { id: "join", title: "加入房间", detail: "输入好友分享的 6 位房间码", action: nav("join", "加入", "join") },
    ],
    actions: [nav("back", "返回首页", "home", "ink")],
  },
  create: {
    id: "create",
    eyebrow: "PRIVATE ROOM",
    title: "创建房间",
    rows: [
      { id: "players", title: "玩家人数", detail: "当前 4 人 · 点按切换 2 - 5 人", badge: "4 人", action: intent("cycle-players", "切换人数", "CycleRoomPlayers") },
      { id: "timer", title: "行动计时", detail: "点按切换 30 / 45 / 60 秒", badge: "45 秒", action: intent("cycle-timer", "切换计时", "CycleTurnSeconds") },
      { id: "bots", title: "机器人补位", detail: "允许机器人补位，点按关闭", badge: "已开启", action: intent("toggle-bots", "关闭", "ToggleRoomBots") },
      { id: "ruleset", title: "规则集（固定）", detail: "original-2025@1 · 版本固定", badge: "基础版" },
    ],
    actions: [intent("create", "创建并邀请", "CreateRoom"), nav("back", "返回", "play-mode", "ink")],
  },
  join: {
    id: "join",
    eyebrow: "JOIN THE CHAOS",
    title: "加入房间",
    subtitle: "输入好友发来的 6 位房间码",
    heroImage: "assets/cats/a-ju.png",
    rows: [{ id: "room-code", title: "房间码", detail: "", badge: "6 位数字" }],
    actions: [{ id: "join", label: "进入房间", tone: "yellow" }, nav("back", "返回", "play-mode", "ink")],
  },
  "lobby-host": {
    id: "lobby-host",
    eyebrow: "ROOM #582913",
    title: "等待开炸",
    subtitle: "你是房主，所有人准备后即可开始",
    rows: LOBBY_HOST_ROWS,
    actions: [
      intent("share", "分享房间码", "ShareRoom"),
      intent("start", "开始游戏", "StartMatch", "cyan"),
      intent("leave", "离开房间", "LeaveRoom", "ink"),
    ],
    scroll: true,
  },
  "lobby-member": {
    id: "lobby-member",
    eyebrow: "ROOM #582913",
    title: "等待开炸",
    subtitle: "房主正在调整规则",
    rows: LOBBY_MEMBER_ROWS,
    actions: [
      intent("ready", "取消准备", "SetReady"),
      nav("rules", "规则图鉴", "rules"),
      intent("leave", "离开房间", "LeaveRoom", "ink"),
    ],
    scroll: true,
  },
  game: {
    id: "game",
    eyebrow: "第 8 回合 · 顺时针 · 32 秒",
    title: "轮到你了",
    table: TABLE_BASE,
    actions: [intent("draw", "抽一张", "Draw"), nav("menu", "菜单", "game-menu", "ink")],
  },
  "other-turn": {
    id: "other-turn",
    eyebrow: "第 8 回合 · 顺时针 · 31 秒",
    title: "等待其他玩家行动",
    subtitle: "等待 阿橘 行动 · 还剩 31 秒",
    table: { ...TABLE_BASE, myTurn: false },
    actions: [nav("menu", "菜单", "game-menu", "ink"), nav("history", "行动记录", "history")],
  },
  attack: {
    id: "attack",
    eyebrow: "攻击已生效 · 当前第 8 回合",
    title: "你还欠 3 个回合！",
    heroLabel: "×3",
    table: { ...TABLE_BASE, turnsOwed: 3 },
    actions: [intent("draw", "抽一张", "Draw"), nav("menu", "菜单", "game-menu", "ink")],
  },
  response: {
    id: "response",
    eyebrow: "否决窗口 · 4 秒",
    title: "有人要否决吗？",
    subtitle: "阿橘打出了攻击，目标是你。再次否决会让原动作重新生效。",
    heroImage: "assets/cats/a-ju.png",
    heroLabel: "4 秒",
    table: { ...TABLE_BASE, myTurn: false },
    actions: [
      intent("nope", "打出否决", "PlayNope", "red"),
      intent("pass", "放行 / 关闭", "PassResponse", "cream"),
    ],
  },
  favor: {
    id: "favor",
    eyebrow: "帮忙 · FAVOR",
    title: "选择目标玩家",
    subtitle: "对方将秘密交出一张牌",
    heroImage: "assets/cards/peek.png",
    rows: PLAYERS.slice(1).map((player) => {
      const selected = player.id === "white";
      return {
        id: player.id,
        title: selected ? `✓ ${player.name}` : player.name,
        detail: selected ? "已选为本次目标" : `${player.handCount} 张手牌`,
        badge: selected ? "已选择" : `${player.handCount} 张`,
        image: player.avatar,
        action: intent(`target-${player.id}`, selected ? "已选择" : "选择", "SelectTarget", "yellow", { targetId: player.id }),
      };
    }),
    actions: [intent("confirm", "确认目标并出牌", "PlayCards", "cyan"), nav("back", "取消", "game", "ink")],
    scroll: true,
  },
  "give-card": {
    id: "give-card",
    eyebrow: "秘密选择 · 12 秒",
    title: "交给团子一张牌",
    subtitle: "接收者：团子 · 已选择：攻击",
    heroImage: "assets/cats/tuan-zi.png",
    heroLabel: "接收者：团子",
    cards: HAND.slice(0, 4),
    actions: [intent("give", "交给团子", "ChooseCard")],
    scroll: true,
  },
  future: {
    id: "future",
    eyebrow: "仅你可见",
    title: "未来的三张牌",
    subtitle: "从左到右依次抽到，查看不会改变顺序",
    heroImage: "assets/cards/peek.png",
    cards: [CARDS.attack, CARDS.skip, CARDS.defuse],
    actions: [intent("done", "记住了", "AcknowledgePeek")],
  },
  explosion: {
    id: "explosion",
    eyebrow: "危险猫出现了！",
    title: "砰！你抽到了危险",
    subtitle: "你有一张拆弹，赶紧化解危机。",
    heroImage: "assets/cards/danger.png",
    heroLabel: "BOOM!",
    actions: [intent("defuse", "使用拆弹", "UseDefuse", "cyan")],
  },
  defuse: {
    id: "defuse",
    eyebrow: "秘密操作 · 15 秒",
    title: "把危险放回哪里？",
    subtitle: "牌堆共 18 张 · 可选牌堆顶至牌堆底",
    heroImage: "assets/cards/defuse.png",
    rows: [
      { id: "position-prev", title: "向牌堆顶移动一格", badge: "向顶", action: intent("position-prev", "向牌堆顶移动一格", "CycleInsertionPosition", "yellow", { delta: -1 }) },
      { id: "position-current", title: "当前位置：第 10 张", detail: "第 10 / 19 个可选位置", badge: "第 10 张" },
      { id: "position-next", title: "向牌堆底移动一格", badge: "向底", action: intent("position-next", "向牌堆底移动一格", "CycleInsertionPosition", "yellow", { delta: 1 }) },
    ],
    actions: [intent("insert", "放回第 10 张", "InsertKitten", "cyan")],
  },
  eliminated: {
    id: "eliminated",
    eyebrow: "砰！",
    title: "你炸毛了",
    subtitle: "别灰心，下一局把危险留给他们。",
    heroImage: "assets/cats/player.png",
    rows: [{ id: "rank", title: "本局名次", detail: "危险猫爆炸", badge: "第 3 名" }],
    actions: [nav("spectate", "继续观战", "other-turn"), intent("leave", "退出房间", "LeaveRoom", "ink")],
  },
  result: {
    id: "result",
    eyebrow: "最后一只猫站着",
    title: "本局结算",
    subtitle: "成功躲过 3 次危险",
    heroImage: "assets/cats/player.png",
    heroLabel: "WINNER · YOU",
    rows: [
      { id: "viewer", title: "你 · 蓝耳队长", detail: "你赢得了本局", badge: "YOU · #1", image: "assets/cats/player.png" },
      { id: "orange", title: "阿橘", detail: "炸毛", badge: "#2", image: "assets/cats/a-ju.png" },
      { id: "gray", title: "小灰", detail: "炸毛", badge: "#3", image: "assets/cats/xiao-hui.png" },
      { id: "white", title: "团子", detail: "炸毛", badge: "#4", image: "assets/cats/tuan-zi.png" },
    ],
    actions: [intent("restart", "再来一局", "RestartMatch"), intent("leave", "回到首页", "LeaveRoom", "cream")],
    scroll: true,
  },
  tutorial: {
    id: "tutorial",
    eyebrow: "1 / 3",
    title: "新手教学",
    subtitle: "你可以连续打出手牌，也可以什么都不出。抽牌会结束当前欠回合。",
    heroImage: "assets/cards/skip.png",
    heroLabel: "STEP 1",
    rows: [{ id: "tutorial-1", title: "先出牌，再抽牌", detail: "● ○ ○" }],
    actions: [intent("next", "下一步", "NextTutorialStep"), nav("back", "返回", "home", "ink")],
  },
  rules: {
    id: "rules",
    eyebrow: "original-2025@1",
    title: "规则图鉴",
    subtitle: "2 - 5 人 · 共 56 张牌",
    rows: RULE_ROWS,
    actions: [nav("back", "返回", "home", "ink")],
    scroll: true,
  },
  "card-detail": {
    id: "card-detail",
    eyebrow: "卡牌详情",
    title: "攻击",
    subtitle: "结束你的回合，让下一位玩家承担两个回合。可被否决，攻击债务可以继续叠加。",
    heroImage: "assets/cards/attack.png",
    rows: [
      { id: "count", title: "基础牌组数量", badge: "4 张" },
      { id: "nope", title: "可否决", badge: "是" },
      { id: "turn", title: "结束回合", badge: "是" },
    ],
    actions: [nav("back", "返回图鉴", "rules")],
    scroll: true,
  },
  history: {
    id: "history",
    eyebrow: "PUBLIC EVENTS",
    title: "行动记录",
    rows: [
      { id: "event-0", title: "阿橘打出了攻击", detail: "公开信息" },
      { id: "event-1", title: "蓝耳队长完成一个回合", detail: "公开信息" },
      { id: "event-2", title: "一名玩家抽了一张牌", detail: "公开信息" },
      { id: "event-3", title: "小灰打出了洗牌", detail: "公开信息" },
      { id: "event-4", title: "团子选择放行", detail: "公开信息" },
      { id: "event-5", title: "牌堆已重新洗牌", detail: "公开信息" },
      { id: "event-6", title: "轮到蓝耳队长行动", detail: "公开信息" },
      { id: "event-7", title: "对局仍在继续", detail: "公开信息" },
    ],
    actions: [nav("back", "返回牌桌", "game")],
    scroll: true,
  },
  "game-menu": {
    id: "game-menu",
    eyebrow: "ROOM #582913",
    title: "对局菜单",
    subtitle: "认输会结束本局操作，但仍可继续观战。",
    heroImage: "assets/cats/player.png",
    rows: [
      { id: "rules", title: "规则图鉴", detail: "卡牌、组合与平台规则", action: nav("rules", "打开", "rules") },
      { id: "settings", title: "声音与振动", detail: "只影响当前设备", action: nav("settings", "打开", "settings") },
      { id: "network", title: "网络状态", detail: "连接与同步信息", action: nav("network", "打开", "network") },
    ],
    actions: [nav("back", "返回牌桌", "game", "cream"), intent("concede", "认输并继续观战", "Concede", "red")],
  },
  network: {
    id: "network",
    eyebrow: "服务端权威对局",
    title: "正在恢复当前牌桌…",
    subtitle: "对局仍由服务器继续处理。重连后会同步当前回合与你的最新私有状态，不会代你自动出牌。",
    heroLabel: "正在同步",
    rows: [
      { id: "state", title: "连接状态", detail: "网络恢复后会自动同步", badge: "离线，等待重连" },
      { id: "turn", title: "当前回合", detail: "阿橘正在行动", badge: "第 8 回合" },
      { id: "revision", title: "恢复方式", detail: "同步完整私有快照", badge: "安全" },
    ],
    actions: [intent("retry", "立即重试", "Reconnect")],
  },
  settings: {
    id: "settings",
    eyebrow: "当前设备",
    title: "设置",
    heroImage: "assets/cats/player.png",
    heroLabel: "蓝耳队长",
    rows: [
      { id: "sound", title: "游戏声音", detail: "卡牌与危险提示音", badge: "已开启", action: intent("toggle-sound", "关闭声音", "ToggleSound") },
      { id: "vibration", title: "触感反馈", detail: "出牌与危险提示", badge: "已开启", action: intent("toggle-vibration", "关闭触感", "ToggleVibration") },
      { id: "tutorial", title: "重看新手教学", detail: "重新查看三步基础教学", action: nav("tutorial", "打开教学", "tutorial") },
      { id: "rules", title: "规则与版本", detail: "查看卡牌、组合与平台规则", action: nav("rules", "打开规则", "rules") },
      { id: "version", title: "当前版本", detail: "original-2025@1", badge: "基础版" },
    ],
    actions: [nav("back", "完成", "home")],
    scroll: true,
  },
} satisfies Readonly<Record<ScreenId, ScreenModel>>);

export const SHORT_SCREEN_FAMILY_REPRESENTATIVES = Object.freeze({
  brand: "home",
  "room-entry": "create",
  lobby: "lobby-host",
  table: "attack",
  choice: "defuse",
  outcome: "result",
  editorial: "rules",
  utility: "settings",
} satisfies Readonly<Record<VisualPreviewFamily, ScreenId>>);

export const PROTOTYPE_REFERENCE_FILES = Object.freeze({
  login: "implementation-login-390x844-final.png",
  home: "implementation-home-390x844-final.png",
  "play-mode": "implementation-play-mode-390x844-final.png",
  create: "implementation-create-390x844-final.png",
  join: "implementation-join-390x844-final.png",
  "lobby-host": "implementation-lobby-390x844-final.png",
  "lobby-member": "implementation-lobby-member-390x844-final.png",
  game: "implementation-game-390x844-final.png",
  "other-turn": "implementation-other-turn-390x844-final.png",
  attack: "implementation-attack-390x844-final.png",
  response: "implementation-response-390x844-final.png",
  favor: "implementation-favor-390x844-final.png",
  "give-card": "implementation-give-card-390x844-final.png",
  future: "implementation-future-390x844-final.png",
  explosion: "implementation-explosion-390x844-final.png",
  defuse: "implementation-defuse-390x844-final.png",
  eliminated: "implementation-eliminated-390x844-final.png",
  result: "implementation-result-390x844-final.png",
  tutorial: "implementation-tutorial-390x844-final.png",
  rules: "implementation-rules-390x844-final.png",
  "card-detail": "implementation-card-detail-390x844-final.png",
  history: "implementation-history-390x844-final.png",
  "game-menu": "implementation-game-menu-390x844-final.png",
  network: "implementation-network-390x844-final.png",
  settings: "implementation-settings-390x844-final.png",
} satisfies Readonly<Record<ScreenId, string>>);
