import type { IStyle } from "minigame-canvas-engine";

export const COLORS = {
  ink: "#171514",
  cream: "#fff1c8",
  paper: "#fff8df",
  yellow: "#ffe11a",
  red: "#ef3d2b",
  cyan: "#00b8c4",
  muted: "#9b8874",
  white: "#ffffff",
} as const;

const commonText: IStyle = { color: COLORS.cream, fontFamily: "sans-serif", whiteSpace: "normal", wordBreak: "break-all" };

export const UI_STYLE: Record<string, IStyle> = {
  app: { width: 390, height: 844, backgroundColor: COLORS.ink, flexDirection: "column", overflow: "hidden" } as IStyle,
  topSafe: { height: 26, flexShrink: 0 },
  homeScreen: { width: 390, height: 844, flexShrink: 0, flexDirection: "column", alignItems: "center", backgroundColor: "#0d0e0d" },
  homeHero: { width: 390, height: 528, flexShrink: 0, imageType: "simple" },
  homeStatusRow: { width: 390, height: 56, flexShrink: 0, flexDirection: "row", alignItems: "center" },
  homeStatusSide: { width: 40, height: 56, flexShrink: 0, imageType: "simple" },
  homeResumeCard: { width: 310, height: 56, paddingLeft: 8, paddingRight: 10, flexShrink: 0, flexDirection: "row", alignItems: "center", backgroundColor: "#0c0c0c", borderWidth: 2, borderColor: "#d8c415", borderRadius: 7, ':active': { transform: "scale(0.985, 0.985)" } },
  homeStatusIcon: { width: 31, height: 44, marginRight: 12, flexShrink: 0, imageType: "simple" },
  homeResumeCopy: { width: 155, height: 44, marginRight: 12, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  homeResumeTitle: { ...commonText, width: 155, height: 22, lineHeight: 22, fontSize: 11, fontWeight: "bold", color: "#e1ca0c", whiteSpace: "nowrap" },
  homeResumeDetail: { ...commonText, width: 155, height: 18, lineHeight: 18, fontSize: 9.5, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  homeResumeLink: { ...commonText, width: 76, height: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.cyan, borderWidth: 1, borderColor: COLORS.cyan, borderRadius: 4, whiteSpace: "nowrap" },
  homeQuickStart: { width: 310, height: 56, paddingLeft: 8, paddingRight: 10, flexShrink: 0, flexDirection: "row", alignItems: "center", backgroundColor: "#0c0c0c", borderWidth: 2, borderColor: "#d8c415", borderRadius: 7 },
  homeQuickStartCopy: { width: 155, height: 44, marginRight: 12, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  homeQuickStartTitle: { ...commonText, width: 155, height: 22, lineHeight: 22, fontSize: 11, fontWeight: "bold", color: "#e1ca0c", whiteSpace: "nowrap" },
  homeQuickStartDetail: { ...commonText, width: 155, height: 18, lineHeight: 18, fontSize: 9.5, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  homeQuickStartReady: { ...commonText, width: 76, height: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.cyan, borderWidth: 1, borderColor: COLORS.cyan, borderRadius: 4, whiteSpace: "nowrap" },
  homeActions: { width: 310, height: 128, paddingTop: 3, flexShrink: 0, flexDirection: "column" },
  homePrimary: { width: 310, height: 61, lineHeight: 61, marginBottom: 7, textAlign: "center", fontSize: 28, fontWeight: "bold", color: "#050505", textStrokeWidth: 0.5, textStrokeColor: "#050505", backgroundColor: "#facf0d", borderWidth: 3, borderColor: "#050505", borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  homeSecondary: { width: 310, height: 57, lineHeight: 57, textAlign: "center", fontSize: 22, fontWeight: "bold", color: "#050505", textStrokeWidth: 0.5, textStrokeColor: "#050505", backgroundColor: "#faeac6", borderWidth: 3, borderColor: "#050505", borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  homeMore: { width: 310, height: 33, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  homeMoreLine: { position: "relative", top: 4, width: 127, height: 1, backgroundColor: "#898476" },
  homeMoreLabel: { ...commonText, position: "relative", top: 4, width: 56, height: 33, lineHeight: 33, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.cream, textStrokeWidth: 2, textStrokeColor: "#0d0e0d" },
  homeUtilities: { width: 310, height: 99, flexShrink: 0, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  homeUtility: { height: 99, flexDirection: "column", alignItems: "center", justifyContent: "flex-start", backgroundColor: "#0d0e0d", borderWidth: 0, ':active': { transform: "scale(0.96, 0.96)" } },
  homeUtilityTutorial: { width: 97 },
  homeUtilityRules: { width: 113 },
  homeUtilitySettings: { width: 98 },
  homeUtilityDivider: { width: 1, height: 44, marginTop: 7, backgroundColor: "#a39d90" },
  homeUtilityImage: { height: 58, imageType: "simple" },
  homeUtilityImageTutorial: { width: 58 },
  homeUtilityImageRules: { width: 72 },
  homeUtilityImageSettings: { width: 62 },
  homeUtilityLabel: { ...commonText, position: "relative", top: -6, height: 24, lineHeight: 24, textAlign: "center", fontSize: 12, fontWeight: "bold", color: COLORS.cream },
  homeUtilityLabelTutorial: { width: 97, fontSize: 12.5 },
  homeUtilityLabelRules: { width: 113 },
  homeUtilityLabelSettings: { width: 98, fontSize: 12.5 },
  createScreen: { width: 390, height: 844, flexShrink: 0, flexDirection: "column", backgroundColor: "#0d0e0d" },
  createHeader: { width: 390, height: 142, paddingLeft: 16, paddingRight: 16, flexShrink: 0, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  createBack: { width: 48, height: 48, marginTop: 10, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#141412", borderWidth: 2, borderColor: COLORS.cream, borderRadius: 6, ':active': { transform: "scale(0.95, 0.95)" } },
  createBackDisabled: { opacity: 0.45, ':active': { transform: "scale(1, 1)" } },
  createBackIcon: { width: 27, height: 27, imageType: "simple" },
  createHeaderCopy: { position: "relative", width: 262, height: 132, paddingTop: 35, flexShrink: 0, flexDirection: "column", alignItems: "center" },
  createHeaderAccent: { position: "absolute", left: -23, top: 55, width: 294, height: 84, imageType: "simple" },
  createEyebrow: { ...commonText, width: 250, height: 22, lineHeight: 22, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.yellow, whiteSpace: "nowrap" },
  createHeaderTitle: { ...commonText, position: "relative", width: 300, height: 61, lineHeight: 57, textAlign: "center", fontSize: 46, fontWeight: "bold", color: COLORS.cream, textStrokeWidth: 2, textStrokeColor: "#050505", whiteSpace: "nowrap" },
  createHeaderSpacer: { width: 48, height: 48, flexShrink: 0 },
  createControlGrid: { width: 364, height: 244, marginLeft: 13, paddingTop: 4, flexShrink: 0, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  createControlsDisabled: { opacity: 0.66 },
  createControlCard: { position: "relative", width: 180, height: 236, paddingTop: 19, flexShrink: 0, flexDirection: "column", alignItems: "center", backgroundColor: "rgba(0, 0, 0, 0)", borderWidth: 0 },
  createControlPanel: { position: "absolute", left: -3, top: -6, width: 188, height: 246, imageType: "simple" },
  createControlCopy: { position: "relative", width: 158, height: 55, flexShrink: 0, flexDirection: "column", alignItems: "center" },
  createControlTitle: { width: 158, height: 31, lineHeight: 30, textAlign: "center", fontSize: 19, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createControlDetail: { width: 158, height: 22, lineHeight: 22, textAlign: "center", fontSize: 13, color: "#6a5d50", whiteSpace: "nowrap" },
  createControlValue: { position: "relative", width: 162, height: 90, flexShrink: 0, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", paddingBottom: 16 },
  createControlNumber: { ...commonText, height: 65, lineHeight: 65, fontSize: 58, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createControlUnit: { ...commonText, height: 37, lineHeight: 34, marginLeft: 4, fontSize: 19, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createStepper: { position: "relative", width: 162, height: 48, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "center" },
  createStepperButton: { width: 46, height: 48, lineHeight: 45, textAlign: "center", fontSize: 25, fontWeight: "bold", color: "#050505", backgroundColor: "#facf0d", borderWidth: 3, borderColor: "#050505", borderRadius: 6, ':active': { transform: "scale(0.94, 0.94)" } },
  createStepperButtonDisabled: { color: "#71695d", backgroundColor: "#c9bfa7", opacity: 0.72, ':active': { transform: "scale(1, 1)" } },
  createStepperCurrent: { width: 70, height: 48, lineHeight: 45, textAlign: "center", fontSize: 17, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#0b0b0a", borderWidth: 3, borderColor: "#050505", whiteSpace: "nowrap" },
  createBotCard: { position: "relative", width: 366, height: 92, marginLeft: 12, marginTop: 13, paddingLeft: 32, paddingRight: 36, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "rgba(0, 0, 0, 0)", borderWidth: 0, ':active': { transform: "scale(0.985, 0.985)" } },
  createBotCardDisabled: { opacity: 0.66, ':active': { transform: "scale(1, 1)" } },
  createBotPanel: { position: "absolute", left: -5, top: -1, width: 376, height: 98, imageType: "simple" },
  createBotCopy: { position: "relative", width: 190, height: 60, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  createBotTitle: { width: 190, height: 34, lineHeight: 33, fontSize: 21, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createBotDetail: { width: 190, height: 24, lineHeight: 23, fontSize: 13, color: "#6a5d50", whiteSpace: "nowrap" },
  createBotToggle: { position: "relative", width: 122, height: 52, padding: 5, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "flex-start", backgroundColor: "#6f645b", borderWidth: 3, borderColor: "#050505", borderRadius: 27 },
  createBotToggleOn: { justifyContent: "flex-end", backgroundColor: COLORS.cyan },
  createBotToggleLabel: { position: "absolute", top: 8, width: 67, height: 30, lineHeight: 30, textAlign: "center", fontSize: 14, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  createBotToggleLabelOn: { left: 3, color: COLORS.cream },
  createBotToggleLabelOff: { right: 3, color: COLORS.cream },
  createBotThumb: { width: 36, height: 36, flexShrink: 0, backgroundColor: COLORS.paper, borderWidth: 3, borderColor: "#050505", borderRadius: 19 },
  createReview: { width: 366, height: 170, marginLeft: 12, marginTop: 20, paddingLeft: 18, paddingRight: 12, paddingTop: 8, flexShrink: 0, flexDirection: "column", backgroundColor: "#0b0b0a", borderWidth: 3, borderColor: "#5d554e", borderRadius: 4 },
  createReviewHeader: { width: 330, height: 43, flexShrink: 0, flexDirection: "row", alignItems: "center" },
  createReviewIcon: { width: 32, height: 32, marginRight: 10, flexShrink: 0, imageType: "simple" },
  createReviewTitle: { ...commonText, width: 286, height: 37, lineHeight: 37, fontSize: 16, fontWeight: "bold", color: COLORS.yellow, whiteSpace: "nowrap" },
  createReviewRow: { position: "relative", width: 330, height: 36, flexShrink: 0, flexDirection: "row", alignItems: "center" },
  createReviewBullet: { width: 22, height: 22, marginLeft: 14, marginRight: 10, flexShrink: 0, imageType: "simple" },
  createReviewText: { ...commonText, width: 270, height: 32, lineHeight: 32, fontSize: 15, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  createReviewDivider: { position: "absolute", left: 54, bottom: 0, width: 276, height: 1, backgroundColor: "#3e3933" },
  createActionDock: { width: 390, height: 138, paddingLeft: 12, paddingRight: 12, paddingTop: 20, flexShrink: 0, flexDirection: "column", alignItems: "center" },
  createPrimary: { position: "relative", width: 366, height: 92, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0, 0, 0, 0)", borderWidth: 0, ':active': { transform: "scale(0.98, 0.98)" } },
  createPrimaryDisabled: { opacity: 0.62 },
  createPrimaryBackground: { position: "absolute", left: -6, top: -4, width: 376, height: 116, imageType: "simple" },
  createPrimaryCopy: { position: "relative", top: -2, width: 338, height: 68, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  createPrimaryLabel: { width: 338, height: 39, lineHeight: 38, textAlign: "center", fontSize: 27, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createPrimaryHint: { width: 338, height: 23, lineHeight: 23, textAlign: "center", fontSize: 11.5, fontWeight: "bold", color: "#5e5145", whiteSpace: "nowrap" },
  createPrimaryHintError: { color: "#7e1711" },
  header: { height: 82, paddingLeft: 16, paddingRight: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0 },
  headerCopy: { flexDirection: "column", alignItems: "center", width: 276 },
  back: { width: 46, height: 46, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  tableMenu: { width: 46, height: 46, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  activityHeaderButton: { position: "relative", width: 46, height: 46, lineHeight: 44, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  activityUnread: { position: "absolute", right: -5, top: -7, width: 22, height: 22, lineHeight: 22, textAlign: "center", fontSize: 9, fontWeight: "bold", color: COLORS.white, backgroundColor: COLORS.red, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 11 },
  headerIcon: { width: 24, height: 24, imageType: "simple" },
  headerSpacer: { width: 46, height: 46 },
  eyebrow: { ...commonText, width: 270, height: 20, lineHeight: 20, fontSize: 10, textAlign: "center", color: COLORS.yellow, fontWeight: "bold" },
  headerTitle: { ...commonText, width: 276, height: 44, lineHeight: 44, fontSize: 28, textAlign: "center", fontWeight: "bold", textStrokeWidth: 1, textStrokeColor: COLORS.ink },
  body: { width: 390, flexGrow: 1, flexShrink: 1, paddingLeft: 16, paddingRight: 16, flexDirection: "column" },
  scroll: { width: 358, marginLeft: 16, flexGrow: 1, flexShrink: 1, flexDirection: "column" },
  hero: { width: 358, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImage: { imageType: "simple" },
  heroHome: { height: 210, minHeight: 210, maxHeight: 210, flexGrow: 0, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImageHome: { width: 168, height: 168 },
  heroResult: { height: 210, minHeight: 210, maxHeight: 210, flexGrow: 0, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImageResult: { width: 170, height: 170 },
  heroWide: { height: 152, minHeight: 152, maxHeight: 152 },
  heroImageWide: { width: 320, height: 100 },
  heroSquare: { height: 210, minHeight: 210, maxHeight: 210 },
  heroImageSquare: { width: 172, height: 172 },
  heroCard: { height: 254, minHeight: 254, maxHeight: 254 },
  heroImageCard: { width: 150, height: 214 },
  heroLabelOnly: { height: 72, minHeight: 72, maxHeight: 72 },
  stackedHeroLabel: { width: 180, height: 36, lineHeight: 36, marginBottom: 2, textAlign: "center", fontSize: 24, fontWeight: "bold", color: COLORS.yellow, textStrokeWidth: 2, textStrokeColor: COLORS.ink },
  stackedHeroLabelHome: { fontSize: 22 },
  stackedHeroLabelResult: { fontSize: 24 },
  stackedHeroLabelWide: { fontSize: 28 },
  stackedHeroLabelCard: { fontSize: 28 },
  stackedHeroLabelSquare: { fontSize: 24 },
  stackedHeroLabelLabelOnly: { width: 250, height: 54, lineHeight: 54, marginBottom: 0, fontSize: 36, textStrokeWidth: 3 },
  subtitle: { ...commonText, width: 340, minHeight: 48, lineHeight: 22, fontSize: 14, textAlign: "center", color: COLORS.cream, paddingTop: 6, paddingBottom: 6 },
  rowList: { width: 358, flexDirection: "column", paddingTop: 4, paddingBottom: 6 },
  row: { width: 350, minHeight: 74, marginLeft: 4, marginBottom: 10, padding: 9, flexDirection: "row", alignItems: "center", backgroundColor: COLORS.cream, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7 },
  rowInteractive: { borderColor: "#76654f", ':active': { transform: "scale(0.985, 0.985)", backgroundColor: COLORS.paper } },
  rowStatic: { backgroundColor: "#e9dfc2", borderColor: "#4a4037" },
  rowSelected: { backgroundColor: COLORS.cyan, borderColor: COLORS.yellow, borderWidth: 4 },
  rowImage: { marginRight: 10, imageType: "simple" },
  rowImageSquare: { width: 54, height: 54, borderRadius: 5 },
  rowImageCard: { width: 42, height: 60, marginLeft: 6, marginRight: 16, borderRadius: 4 },
  rowImageResult: { width: 54, height: 54, borderRadius: 27, borderWidth: 2, borderColor: COLORS.ink, backgroundColor: "#23201d" },
  rowCopy: { flexGrow: 1, flexShrink: 1, flexDirection: "column", justifyContent: "center" },
  rowCopyControl: { width: 158, flexGrow: 0, flexShrink: 0 },
  rowTitle: { width: 205, minHeight: 26, lineHeight: 24, fontSize: 16, fontWeight: "bold", color: COLORS.ink, whiteSpace: "normal", wordBreak: "break-all" },
  rowDetail: { width: 205, minHeight: 34, lineHeight: 16, fontSize: 11, color: "#5e5145", whiteSpace: "normal", wordBreak: "break-all" },
  rowTextControl: { width: 158 },
  badge: { width: 62, minHeight: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderRadius: 15 },
  rowChevron: { width: 22, height: 22, marginLeft: 8, imageType: "simple" },
  toggle: { width: 62, height: 44, padding: 8, marginLeft: 8, flexDirection: "row", alignItems: "center", justifyContent: "flex-start", backgroundColor: "#6f645b", borderWidth: 2, borderColor: COLORS.ink, borderRadius: 22, ':active': { transform: "scale(0.95, 0.95)" } },
  toggleOn: { justifyContent: "flex-end", backgroundColor: COLORS.cyan },
  toggleThumb: { width: 24, height: 24, backgroundColor: COLORS.paper, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 12 },
  stepper: { width: 164, height: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  stepperButton: { width: 44, height: 44, lineHeight: 42, textAlign: "center", fontSize: 24, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 6, ':active': { transform: "scale(0.94, 0.94)" } },
  stepperValue: { width: 72, height: 44, lineHeight: 44, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.ink, whiteSpace: "nowrap", textOverflow: "ellipsis" },
  selectionMark: { width: 36, height: 36, marginLeft: 8, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: COLORS.paper, borderWidth: 3, borderColor: "#7a6a56", borderRadius: 18 },
  selectionMarkSelected: { backgroundColor: COLORS.yellow, borderColor: COLORS.ink },
  selectionCheck: { width: 20, height: 20, imageType: "simple" },
  actionDock: { width: 390, minHeight: 92, maxHeight: 270, paddingLeft: 16, paddingRight: 16, paddingTop: 9, paddingBottom: 16, flexDirection: "column", justifyContent: "flex-end", flexShrink: 0 },
  actionRow: { width: 358, height: 60, flexDirection: "row", justifyContent: "space-between" },
  tableActionDock: { width: 390, height: 96, paddingLeft: 16, paddingRight: 16, paddingTop: 10, paddingBottom: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0, backgroundColor: "#12110f", borderWidth: 2, borderColor: "#302b26" },
  tableDockHint: { ...commonText, width: 358, height: 58, lineHeight: 58, textAlign: "center", fontSize: 14, fontWeight: "bold", color: COLORS.cream },
  tableCancelButton: { width: 108, height: 58, lineHeight: 58, textAlign: "center", fontSize: 17, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#12110f", borderWidth: 2, borderColor: "#5d554e", borderRadius: 7, ':active': { transform: "scale(0.97, 0.97)" } },
  tablePrimaryButton: { width: 232, height: 58, lineHeight: 58, textAlign: "center", fontSize: 20, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  tablePrimaryDisabled: { width: 232, height: 58, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#39342e", borderWidth: 2, borderColor: "#5d554e", borderRadius: 7 },
  tablePrimaryDisabledText: { ...commonText, width: 228, height: 56, lineHeight: 56, textAlign: "center", fontSize: 16, fontWeight: "bold", color: "#b8ab98" },
  button: { width: 358, height: 52, lineHeight: 52, marginBottom: 8, textAlign: "center", fontSize: 16, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  buttonCompact: { width: 175, fontSize: 14 },
  buttonDisabled: { flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#39342e", borderColor: "#5d554e" },
  buttonDisabledText: { ...commonText, width: 352, height: 48, lineHeight: 48, textAlign: "center", fontSize: 15, fontWeight: "bold", color: "#b8ab98" },
  buttonCream: { backgroundColor: COLORS.cream },
  buttonCyan: { backgroundColor: COLORS.cyan, color: COLORS.ink },
  buttonRed: { backgroundColor: COLORS.red, color: COLORS.white },
  buttonInk: { backgroundColor: "#292624", color: COLORS.cream, borderColor: "#5d554e" },
  cardGrid: { width: 358, flexShrink: 0, flexDirection: "column", alignItems: "center", paddingTop: 8 },
  cardGridRow: { width: 358, height: 170, flexShrink: 0, flexDirection: "row", justifyContent: "center", alignItems: "center" },
  cardItem: { position: "relative", width: 96, height: 154, margin: 8, flexDirection: "column", alignItems: "center", backgroundColor: COLORS.cream, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7 },
  cardSelected: { backgroundColor: COLORS.cyan, borderWidth: 5, borderColor: COLORS.yellow },
  cardImage: { width: 90, height: 129, borderRadius: 4, imageType: "simple" },
  cardCheck: { position: "absolute", right: 3, top: 3, width: 28, height: 28, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 14 },
  cardCheckIcon: { width: 16, height: 16, imageType: "simple" },
  cardName: { width: 90, height: 25, lineHeight: 25, textAlign: "center", color: COLORS.ink, fontSize: 11, fontWeight: "bold" },
  players: { width: 358, minHeight: 95, flexDirection: "row", justifyContent: "space-around", alignItems: "center", flexShrink: 0 },
  player: { width: 68, height: 92, flexDirection: "column", alignItems: "center", justifyContent: "center", borderRadius: 6 },
  playerActive: { backgroundColor: "#2f2a25", borderWidth: 2, borderColor: COLORS.yellow },
  avatar: { width: 54, height: 54, borderRadius: 27, borderWidth: 3, borderColor: COLORS.cream },
  avatarActive: { borderColor: COLORS.yellow, borderWidth: 4 },
  playerName: { width: 66, height: 22, lineHeight: 22, textAlign: "center", color: COLORS.cream, fontSize: 10, fontWeight: "bold", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  playerStatus: { ...commonText, width: 66, height: 14, lineHeight: 14, textAlign: "center", color: "#8f8275", fontSize: 8, fontWeight: "bold", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  playerStatusActive: { color: COLORS.yellow },
  tableCanvas: { width: 358, flexGrow: 0, flexShrink: 0 },
  activityBanner: { width: 358, height: 48, paddingLeft: 10, paddingRight: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0, backgroundColor: "#2a2725", borderWidth: 2, borderColor: "#5d554e", borderRadius: 6, ':active': { transform: "scale(0.99, 0.99)" } },
  activityBannerNeutral: { borderColor: "#766b60" },
  activityBannerAction: { borderColor: COLORS.cyan },
  activityBannerDanger: { borderColor: COLORS.red },
  activityBannerSuccess: { borderColor: COLORS.yellow },
  activityBannerFresh: { backgroundColor: "#39332d", borderWidth: 3 },
  activityBannerCopy: { width: 282, height: 40, flexDirection: "column", justifyContent: "center" },
  activityBannerTitle: { ...commonText, width: 282, height: 22, lineHeight: 22, fontSize: 12, fontWeight: "bold", color: COLORS.cream, textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityBannerDetail: { ...commonText, width: 282, height: 16, lineHeight: 16, fontSize: 9, color: "#b8ab98", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityBannerLink: { ...commonText, width: 42, height: 32, lineHeight: 32, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.yellow },
  activityBackdrop: { position: "absolute", left: 0, top: 0, width: 390, height: 844, backgroundColor: "rgba(0, 0, 0, 0.72)" },
  activitySheet: { position: "absolute", left: 0, top: 422, width: 390, height: 422, paddingLeft: 16, paddingRight: 16, paddingTop: 14, flexDirection: "column", backgroundColor: "#211e1b", borderWidth: 3, borderColor: COLORS.cream, borderRadius: 7 },
  activitySheetHeader: { width: 352, height: 68, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  activitySheetCopy: { width: 250, height: 60, flexDirection: "column", justifyContent: "center" },
  activitySheetEyebrow: { ...commonText, width: 250, height: 18, lineHeight: 18, fontSize: 9, fontWeight: "bold", color: COLORS.cyan },
  activitySheetTitle: { ...commonText, width: 250, height: 36, lineHeight: 36, fontSize: 26, fontWeight: "bold", color: COLORS.cream },
  activityClose: { width: 72, height: 44, lineHeight: 42, textAlign: "center", fontSize: 12, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.cream, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 6, ':active': { transform: "scale(0.96, 0.96)" } },
  activityPrivacy: { width: 352, height: 40, paddingLeft: 10, flexDirection: "column", justifyContent: "center", backgroundColor: "#302b26", borderRadius: 5 },
  activityPrivacyText: { ...commonText, width: 332, height: 28, lineHeight: 28, fontSize: 10, color: "#c9baa4" },
  activityTimeline: { width: 352, height: 260, paddingTop: 10, flexDirection: "column", justifyContent: "flex-end" },
  activityTimelineRow: { width: 352, height: 54, flexDirection: "row", alignItems: "center", borderWidth: 0, borderBottomWidth: 1, borderColor: "#4c443d" },
  activityTimelineMarker: { width: 10, height: 10, marginLeft: 4, marginRight: 12, borderRadius: 5, backgroundColor: "#8f8275" },
  activityTimelineMarkerNeutral: { backgroundColor: "#8f8275" },
  activityTimelineMarkerAction: { backgroundColor: COLORS.cyan },
  activityTimelineMarkerDanger: { backgroundColor: COLORS.red },
  activityTimelineMarkerSuccess: { backgroundColor: COLORS.yellow },
  activityTimelineCopy: { width: 316, height: 50, flexDirection: "column", justifyContent: "center" },
  activityTimelineTitle: { ...commonText, width: 316, height: 27, lineHeight: 27, fontSize: 13, fontWeight: "bold", color: COLORS.cream, textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityTimelineDetail: { ...commonText, width: 316, height: 18, lineHeight: 18, fontSize: 9, color: "#a99a88" },
  activityEmpty: { width: 352, height: 220, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  activityEmptyTitle: { ...commonText, width: 320, height: 30, lineHeight: 30, textAlign: "center", fontSize: 16, fontWeight: "bold", color: COLORS.cream },
  activityEmptyDetail: { ...commonText, width: 320, height: 24, lineHeight: 24, textAlign: "center", fontSize: 10, color: "#a99a88" },
  error: { position: "absolute", left: 20, top: 106, width: 350, minHeight: 42, lineHeight: 20, padding: 10, textAlign: "center", color: COLORS.white, backgroundColor: COLORS.red, borderRadius: 6, borderWidth: 2, borderColor: COLORS.ink, fontSize: 11, fontWeight: "bold" },
};
