import type { IStyle } from "minigame-canvas-engine";

export const COLORS = {
  ink: "#171514",
  cream: "#fff1c8",
  paper: "#fff8df",
  yellow: "#ffe11a",
  red: "#ef3d2b",
  cyan: "#00b8c4",
  muted: "#9b8874",
  white: "#ffffff",
} as const;

const commonText: IStyle = { color: COLORS.cream, fontFamily: "sans-serif", whiteSpace: "normal", wordBreak: "break-all" };

export const UI_STYLE: Record<string, IStyle> = {
  app: { width: 390, height: 844, backgroundColor: COLORS.ink, flexDirection: "column", overflow: "hidden" } as IStyle,
  topSafe: { height: 26, flexShrink: 0 },
  homeScreen: { width: 390, height: 844, flexShrink: 0, flexDirection: "column", alignItems: "center", backgroundColor: "#0d0e0d" },
  homeHero: { width: 390, height: 528, flexShrink: 0, imageType: "simple" },
  homeStatusRow: { width: 390, height: 56, flexShrink: 0, flexDirection: "row", alignItems: "center" },
  homeStatusSide: { width: 40, height: 56, flexShrink: 0, imageType: "simple" },
  homeResumeCard: { width: 310, height: 56, paddingLeft: 8, paddingRight: 10, flexShrink: 0, flexDirection: "row", alignItems: "center", backgroundColor: "#0c0c0c", borderWidth: 2, borderColor: "#d8c415", borderRadius: 7, ':active': { transform: "scale(0.985, 0.985)" } },
  homeStatusIcon: { width: 31, height: 44, marginRight: 12, flexShrink: 0, imageType: "simple" },
  homeResumeCopy: { width: 155, height: 44, marginRight: 12, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  homeResumeTitle: { ...commonText, width: 155, height: 22, lineHeight: 22, fontSize: 11, fontWeight: "bold", color: "#e1ca0c", whiteSpace: "nowrap" },
  homeResumeDetail: { ...commonText, width: 155, height: 18, lineHeight: 18, fontSize: 9.5, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  homeResumeLink: { ...commonText, width: 76, height: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.cyan, borderWidth: 1, borderColor: COLORS.cyan, borderRadius: 4, whiteSpace: "nowrap" },
  homeQuickStart: { width: 310, height: 56, paddingLeft: 8, paddingRight: 10, flexShrink: 0, flexDirection: "row", alignItems: "center", backgroundColor: "#0c0c0c", borderWidth: 2, borderColor: "#d8c415", borderRadius: 7 },
  homeQuickStartCopy: { width: 155, height: 44, marginRight: 12, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  homeQuickStartTitle: { ...commonText, width: 155, height: 22, lineHeight: 22, fontSize: 11, fontWeight: "bold", color: "#e1ca0c", whiteSpace: "nowrap" },
  homeQuickStartDetail: { ...commonText, width: 155, height: 18, lineHeight: 18, fontSize: 9.5, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  homeQuickStartReady: { ...commonText, width: 76, height: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.cyan, borderWidth: 1, borderColor: COLORS.cyan, borderRadius: 4, whiteSpace: "nowrap" },
  homeActions: { width: 310, height: 128, paddingTop: 3, flexShrink: 0, flexDirection: "column" },
  homePrimary: { width: 310, height: 61, lineHeight: 61, marginBottom: 7, textAlign: "center", fontSize: 28, fontWeight: "bold", color: "#050505", textStrokeWidth: 0.5, textStrokeColor: "#050505", backgroundColor: "#facf0d", borderWidth: 3, borderColor: "#050505", borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  homeSecondary: { width: 310, height: 57, lineHeight: 57, textAlign: "center", fontSize: 22, fontWeight: "bold", color: "#050505", textStrokeWidth: 0.5, textStrokeColor: "#050505", backgroundColor: "#faeac6", borderWidth: 3, borderColor: "#050505", borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  homeMore: { width: 310, height: 33, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  homeMoreLine: { position: "relative", top: 4, width: 127, height: 1, backgroundColor: "#898476" },
  homeMoreLabel: { ...commonText, position: "relative", top: 4, width: 56, height: 33, lineHeight: 33, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.cream, textStrokeWidth: 2, textStrokeColor: "#0d0e0d" },
  homeUtilities: { width: 310, height: 99, flexShrink: 0, flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between" },
  homeUtility: { height: 99, flexDirection: "column", alignItems: "center", justifyContent: "flex-start", backgroundColor: "#0d0e0d", borderWidth: 0, ':active': { transform: "scale(0.96, 0.96)" } },
  homeUtilityTutorial: { width: 97 },
  homeUtilityRules: { width: 113 },
  homeUtilitySettings: { width: 98 },
  homeUtilityDivider: { width: 1, height: 44, marginTop: 7, backgroundColor: "#a39d90" },
  homeUtilityImage: { height: 58, imageType: "simple" },
  homeUtilityImageTutorial: { width: 58 },
  homeUtilityImageRules: { width: 72 },
  homeUtilityImageSettings: { width: 62 },
  homeUtilityLabel: { ...commonText, position: "relative", top: -6, height: 24, lineHeight: 24, textAlign: "center", fontSize: 12, fontWeight: "bold", color: COLORS.cream },
  homeUtilityLabelTutorial: { width: 97, fontSize: 12.5 },
  homeUtilityLabelRules: { width: 113 },
  homeUtilityLabelSettings: { width: 98, fontSize: 12.5 },
  createScreen: { position: "relative", width: 390, height: 844, flexShrink: 0, backgroundColor: "#050404" },
  createScroll: { width: 390, height: 844, flexShrink: 0 },
  createCanvas: { position: "relative", width: 390, height: 844, flexShrink: 0 },
  createArtboard: { position: "absolute", left: 0, top: 0, width: 390, height: 844, imageType: "simple" },
  createHot: { position: "absolute", borderWidth: 0, backgroundColor: "rgba(0, 0, 0, 0)", ':active': { backgroundColor: "rgba(255, 255, 255, 0.14)" } },
  createHotDisabled: { backgroundColor: "rgba(82, 74, 61, 0.44)", ':active': { backgroundColor: "rgba(82, 74, 61, 0.44)" } },
  createBackHot: { left: 16, top: 35, width: 49, height: 48, borderRadius: 7 },
  createRowHit: { position: "absolute", width: 0, height: 0, opacity: 0 },
  createPlayerDown: { left: 20, top: 332, width: 50, height: 57, borderRadius: 8 },
  createPlayerUp: { left: 137, top: 332, width: 50, height: 57, borderRadius: 8 },
  createTimerDown: { left: 203, top: 332, width: 51, height: 57, borderRadius: 8 },
  createTimerUp: { left: 320, top: 332, width: 51, height: 57, borderRadius: 8 },
  createBotHot: { left: 13, top: 423, width: 365, height: 98 },
  createRulesHit: { position: "absolute", left: 13, top: 535, width: 365, height: 172 },
  createPrimaryHot: { left: 13, top: 728, width: 365, height: 93 },
  createActionAlias: { position: "absolute", left: 0, top: 0, width: 0, height: 0, opacity: 0, borderWidth: 0 },
  createStatePaperPatch: { position: "absolute", height: 68, flexDirection: "row", alignItems: "flex-end", justifyContent: "center", paddingBottom: 4, backgroundColor: "#f6e4be" },
  createPlayerLargePatch: { left: 59, top: 257, width: 107 },
  createTimerLargePatch: { left: 229, top: 257, width: 136 },
  createStateNumber: { ...commonText, height: 58, lineHeight: 58, fontSize: 50, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createStateUnit: { ...commonText, height: 33, lineHeight: 31, marginLeft: 2, fontSize: 17, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  createStateCurrent: { ...commonText, position: "absolute", top: 337, width: 79, height: 46, lineHeight: 44, textAlign: "center", fontSize: 16, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#050505", whiteSpace: "nowrap" },
  createPlayerCurrentPatch: { left: 64 },
  createTimerCurrentPatch: { left: 249 },
  createReviewStateRow: { ...commonText, position: "absolute", left: 78, width: 232, height: 31, lineHeight: 30, fontSize: 14, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#050505", whiteSpace: "nowrap" },
  createReviewPlayersPatch: { top: 589 },
  createReviewTimerPatch: { top: 626 },
  createReviewBotsPatch: { top: 663 },
  createBotStatePatch: { position: "absolute", left: 224, top: 444, width: 132, height: 61, paddingLeft: 8, paddingTop: 6, backgroundColor: "#f6e4be" },
  createBotStateToggle: { position: "relative", width: 116, height: 49, backgroundColor: "#6f645b", borderWidth: 3, borderColor: "#050505", borderRadius: 26 },
  createBotStateLabel: { ...commonText, position: "absolute", right: 8, top: 8, width: 66, height: 29, lineHeight: 29, textAlign: "center", fontSize: 13, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  createBotStateThumb: { position: "absolute", left: 5, top: 4, width: 35, height: 35, backgroundColor: "#f7ead0", borderWidth: 3, borderColor: "#050505", borderRadius: 19 },
  createPrimarySendingShade: { position: "absolute", left: 13, top: 728, width: 365, height: 93, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(5, 5, 5, 0.58)" },
  createPrimarySendingLabel: { ...commonText, width: 330, height: 38, lineHeight: 38, textAlign: "center", fontSize: 25, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  createPrimarySendingHint: { ...commonText, width: 330, height: 22, lineHeight: 22, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  createPrimaryErrorPatch: { ...commonText, position: "absolute", left: 80, top: 786, width: 230, height: 22, lineHeight: 22, textAlign: "center", fontSize: 11, fontWeight: "bold", color: "#7e1711", backgroundColor: "#fccc03", whiteSpace: "nowrap" },
  defuseScreen: { width: 390, height: 844, flexShrink: 0, flexDirection: "column", backgroundColor: "#0d0e0d" },
  defuseHeader: { width: 390, height: 100, paddingLeft: 16, paddingRight: 16, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  defuseHeaderSpacer: { width: 46, height: 46, flexShrink: 0 },
  defuseHeaderCopy: { position: "relative", width: 258, height: 98, paddingTop: 8, flexShrink: 0, flexDirection: "column", alignItems: "center" },
  defuseHeaderAccent: { position: "absolute", left: -26, top: 31, width: 310, height: 62, imageType: "simple" },
  defuseEyebrow: { ...commonText, position: "relative", width: 250, height: 19, lineHeight: 19, textAlign: "center", fontSize: 10.5, fontWeight: "bold", color: COLORS.yellow, whiteSpace: "nowrap" },
  defuseHeaderTitle: { ...commonText, position: "relative", width: 292, height: 52, lineHeight: 50, textAlign: "center", fontSize: 34, fontWeight: "bold", color: COLORS.cream, textStrokeWidth: 2, textStrokeColor: "#050505", whiteSpace: "nowrap" },
  defuseActivityWrap: { width: 390, height: 54, paddingLeft: 16, flexShrink: 0, flexDirection: "row", alignItems: "center" },
  defuseBody: { width: 390, minHeight: 0, flexGrow: 1, flexShrink: 1, flexDirection: "column", alignItems: "center", justifyContent: "space-around" },
  defuseSecretStage: { width: 358, height: 220, flexShrink: 0, flexDirection: "column", backgroundColor: "#171310", borderWidth: 2, borderColor: "#724035", borderRightWidth: 6, borderBottomWidth: 6, borderRadius: 3 },
  defuseSecretStrip: { width: 350, height: 38, paddingLeft: 10, paddingRight: 9, flexShrink: 0, flexDirection: "row", alignItems: "center", backgroundColor: "#2a201a", borderBottomWidth: 2, borderColor: "#724035" },
  defuseSecretIcon: { width: 22, height: 22, marginRight: 8, flexShrink: 0, imageType: "simple" },
  defuseSecretCopy: { width: 194, height: 34, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  defuseSecretTitle: { ...commonText, width: 194, height: 19, lineHeight: 19, fontSize: 13.5, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  defuseSecretDetail: { ...commonText, width: 194, height: 14, lineHeight: 14, fontSize: 9.5, color: "#c8b8a3", whiteSpace: "nowrap" },
  defuseSecretBadge: { ...commonText, width: 90, height: 27, lineHeight: 27, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.cyan, borderWidth: 2, borderColor: "#050505", whiteSpace: "nowrap" },
  defuseTransferRow: { width: 350, height: 182, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "center" },
  defuseTransferBlock: { position: "relative", width: 122, height: 174, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  defuseDangerCard: { width: 105, height: 150, flexShrink: 0, imageType: "simple", borderWidth: 3, borderColor: COLORS.cream, borderRightWidth: 7, borderBottomWidth: 7, transform: "rotate(-2deg)" },
  defuseDeckCard: { width: 86, height: 123, flexShrink: 0, imageType: "simple", borderWidth: 3, borderColor: COLORS.cream, borderRightWidth: 7, borderBottomWidth: 7, transform: "rotate(2deg)" },
  defuseTransferLabel: { ...commonText, position: "absolute", bottom: 0, height: 25, lineHeight: 25, textAlign: "center", fontSize: 13, fontWeight: "bold", color: "#050505", borderWidth: 2, borderColor: "#050505", whiteSpace: "nowrap" },
  defuseDangerLabel: { width: 78, left: 22, backgroundColor: COLORS.red, color: COLORS.white, transform: "rotate(-3deg)" },
  defuseDeckLabel: { width: 104, left: 9, backgroundColor: COLORS.yellow, transform: "rotate(2deg)" },
  defuseDeckBlock: { justifyContent: "center" },
  defuseTransferArrow: { width: 76, height: 116, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  defuseTransferArrowBox: { width: 48, height: 48, padding: 10, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: COLORS.cyan, borderWidth: 3, borderColor: "#050505", transform: "rotate(-3deg)" },
  defuseTransferArrowIcon: { width: 25, height: 25, imageType: "simple" },
  defuseTransferArrowText: { ...commonText, width: 74, height: 24, lineHeight: 24, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.cream, whiteSpace: "nowrap" },
  defusePicker: { width: 358, height: 208, paddingLeft: 10, paddingRight: 10, paddingTop: 7, paddingBottom: 7, flexShrink: 0, flexDirection: "column", backgroundColor: COLORS.cream, borderWidth: 3, borderColor: "#050505", borderRightWidth: 7, borderBottomWidth: 7, borderRadius: 3 },
  defusePickerHeader: { width: 332, height: 44, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  defusePickerCopy: { width: 225, height: 42, flexShrink: 0, flexDirection: "column", justifyContent: "center" },
  defusePickerTitle: { width: 225, height: 24, lineHeight: 24, fontSize: 17.5, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  defusePickerDetail: { width: 225, height: 17, lineHeight: 17, fontSize: 10.5, color: "#665849", whiteSpace: "nowrap" },
  defusePickerCount: { ...commonText, width: 92, height: 31, lineHeight: 31, textAlign: "center", fontSize: 16, fontWeight: "bold", color: "#050505", backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: "#050505", whiteSpace: "nowrap" },
  defusePositionGuide: { width: 332, height: 37, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  defuseEndpoint: { width: 55, height: 24, lineHeight: 24, textAlign: "center", fontSize: 9.5, fontWeight: "bold", color: "#665849", whiteSpace: "nowrap" },
  defuseGuideTrack: { position: "relative", width: 210, height: 12, flexShrink: 0, backgroundColor: "#6c6052", borderWidth: 2, borderColor: "#050505" },
  defuseGuideFill: { position: "absolute", left: 0, top: 0, width: 4, height: 8, backgroundColor: COLORS.cyan },
  defuseGuideMarker: { position: "absolute", left: 0, top: -5, width: 18, height: 18, backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: "#050505", borderRadius: 9 },
  defusePositionControl: { width: 332, height: 74, flexShrink: 0, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  defuseStepButton: { width: 72, height: 64, lineHeight: 61, flexShrink: 0, textAlign: "center", fontSize: 13.5, fontWeight: "bold", color: "#050505", backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: "#050505", borderRadius: 3, whiteSpace: "nowrap", ':active': { transform: "scale(0.95, 0.95)" } },
  defuseStepButtonDisabled: { color: "#746b60", backgroundColor: "#c9bfa7", opacity: 0.58, ':active': { transform: "scale(1, 1)" } },
  defuseCurrentPosition: { width: 174, height: 66, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#0b0b0a", borderWidth: 3, borderColor: "#050505" },
  defuseCurrentLabel: { ...commonText, width: 168, height: 32, lineHeight: 31, textAlign: "center", fontSize: 21, fontWeight: "bold", color: COLORS.yellow, whiteSpace: "nowrap" },
  defuseCurrentDetail: { ...commonText, width: 168, height: 21, lineHeight: 20, textAlign: "center", fontSize: 9.5, color: COLORS.cream, whiteSpace: "nowrap" },
  defuseActionDock: { width: 390, height: 128, paddingLeft: 12, paddingRight: 12, paddingTop: 8, paddingBottom: 12, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "flex-start" },
  defusePrimary: { position: "relative", width: 366, height: 92, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "rgba(0, 0, 0, 0)", borderWidth: 0, ':active': { transform: "scale(0.98, 0.98)" } },
  defusePrimaryDisabled: { opacity: 0.62, ':active': { transform: "scale(1, 1)" } },
  defusePrimaryBackground: { position: "absolute", left: -5, top: -4, width: 376, height: 116, imageType: "simple" },
  defusePrimaryCopy: { position: "relative", top: -2, width: 338, height: 66, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  defusePrimaryLabel: { width: 338, height: 37, lineHeight: 36, textAlign: "center", fontSize: 25, fontWeight: "bold", color: "#050505", whiteSpace: "nowrap" },
  defusePrimaryHint: { width: 338, height: 21, lineHeight: 21, textAlign: "center", fontSize: 10.5, fontWeight: "bold", color: "#5e5145", whiteSpace: "nowrap" },
  defuseError: { top: 142 },
  header: { height: 82, paddingLeft: 16, paddingRight: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0 },
  headerCopy: { flexDirection: "column", alignItems: "center", width: 276 },
  back: { width: 46, height: 46, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  tableMenu: { width: 46, height: 46, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  activityHeaderButton: { position: "relative", width: 46, height: 46, lineHeight: 44, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#2a2725", borderRadius: 6, borderWidth: 2, borderColor: COLORS.cream, ':active': { transform: "scale(0.95, 0.95)" } },
  activityUnread: { position: "absolute", right: -5, top: -7, width: 22, height: 22, lineHeight: 22, textAlign: "center", fontSize: 9, fontWeight: "bold", color: COLORS.white, backgroundColor: COLORS.red, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 11 },
  headerIcon: { width: 24, height: 24, imageType: "simple" },
  headerSpacer: { width: 46, height: 46 },
  eyebrow: { ...commonText, width: 270, height: 20, lineHeight: 20, fontSize: 10, textAlign: "center", color: COLORS.yellow, fontWeight: "bold" },
  headerTitle: { ...commonText, width: 276, height: 44, lineHeight: 44, fontSize: 28, textAlign: "center", fontWeight: "bold", textStrokeWidth: 1, textStrokeColor: COLORS.ink },
  body: { width: 390, flexGrow: 1, flexShrink: 1, paddingLeft: 16, paddingRight: 16, flexDirection: "column" },
  scroll: { width: 358, marginLeft: 16, flexGrow: 1, flexShrink: 1, flexDirection: "column" },
  hero: { width: 358, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImage: { imageType: "simple" },
  heroHome: { height: 210, minHeight: 210, maxHeight: 210, flexGrow: 0, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImageHome: { width: 168, height: 168 },
  heroResult: { height: 210, minHeight: 210, maxHeight: 210, flexGrow: 0, flexShrink: 0, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  heroImageResult: { width: 170, height: 170 },
  heroWide: { height: 152, minHeight: 152, maxHeight: 152 },
  heroImageWide: { width: 320, height: 100 },
  heroSquare: { height: 210, minHeight: 210, maxHeight: 210 },
  heroImageSquare: { width: 172, height: 172 },
  heroCard: { height: 254, minHeight: 254, maxHeight: 254 },
  heroImageCard: { width: 150, height: 214 },
  heroLabelOnly: { height: 72, minHeight: 72, maxHeight: 72 },
  stackedHeroLabel: { width: 180, height: 36, lineHeight: 36, marginBottom: 2, textAlign: "center", fontSize: 24, fontWeight: "bold", color: COLORS.yellow, textStrokeWidth: 2, textStrokeColor: COLORS.ink },
  stackedHeroLabelHome: { fontSize: 22 },
  stackedHeroLabelResult: { fontSize: 24 },
  stackedHeroLabelWide: { fontSize: 28 },
  stackedHeroLabelCard: { fontSize: 28 },
  stackedHeroLabelSquare: { fontSize: 24 },
  stackedHeroLabelLabelOnly: { width: 250, height: 54, lineHeight: 54, marginBottom: 0, fontSize: 36, textStrokeWidth: 3 },
  subtitle: { ...commonText, width: 340, minHeight: 48, lineHeight: 22, fontSize: 14, textAlign: "center", color: COLORS.cream, paddingTop: 6, paddingBottom: 6 },
  rowList: { width: 358, flexDirection: "column", paddingTop: 4, paddingBottom: 6 },
  row: { width: 350, minHeight: 74, marginLeft: 4, marginBottom: 10, padding: 9, flexDirection: "row", alignItems: "center", backgroundColor: COLORS.cream, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7 },
  rowInteractive: { borderColor: "#76654f", ':active': { transform: "scale(0.985, 0.985)", backgroundColor: COLORS.paper } },
  rowStatic: { backgroundColor: "#e9dfc2", borderColor: "#4a4037" },
  rowSelected: { backgroundColor: COLORS.cyan, borderColor: COLORS.yellow, borderWidth: 4 },
  rowImage: { marginRight: 10, imageType: "simple" },
  rowImageSquare: { width: 54, height: 54, borderRadius: 5 },
  rowImageCard: { width: 42, height: 60, marginLeft: 6, marginRight: 16, borderRadius: 4 },
  rowImageResult: { width: 54, height: 54, borderRadius: 27, borderWidth: 2, borderColor: COLORS.ink, backgroundColor: "#23201d" },
  rowCopy: { flexGrow: 1, flexShrink: 1, flexDirection: "column", justifyContent: "center" },
  rowCopyControl: { width: 158, flexGrow: 0, flexShrink: 0 },
  rowTitle: { width: 205, minHeight: 26, lineHeight: 24, fontSize: 16, fontWeight: "bold", color: COLORS.ink, whiteSpace: "normal", wordBreak: "break-all" },
  rowDetail: { width: 205, minHeight: 34, lineHeight: 16, fontSize: 11, color: "#5e5145", whiteSpace: "normal", wordBreak: "break-all" },
  rowTextControl: { width: 158 },
  badge: { width: 62, minHeight: 30, lineHeight: 30, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderRadius: 15 },
  rowChevron: { width: 22, height: 22, marginLeft: 8, imageType: "simple" },
  toggle: { width: 62, height: 44, padding: 8, marginLeft: 8, flexDirection: "row", alignItems: "center", justifyContent: "flex-start", backgroundColor: "#6f645b", borderWidth: 2, borderColor: COLORS.ink, borderRadius: 22, ':active': { transform: "scale(0.95, 0.95)" } },
  toggleOn: { justifyContent: "flex-end", backgroundColor: COLORS.cyan },
  toggleThumb: { width: 24, height: 24, backgroundColor: COLORS.paper, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 12 },
  stepper: { width: 164, height: 46, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  stepperButton: { width: 44, height: 44, lineHeight: 42, textAlign: "center", fontSize: 24, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 6, ':active': { transform: "scale(0.94, 0.94)" } },
  stepperValue: { width: 72, height: 44, lineHeight: 44, textAlign: "center", fontSize: 11, fontWeight: "bold", color: COLORS.ink, whiteSpace: "nowrap", textOverflow: "ellipsis" },
  selectionMark: { width: 36, height: 36, marginLeft: 8, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: COLORS.paper, borderWidth: 3, borderColor: "#7a6a56", borderRadius: 18 },
  selectionMarkSelected: { backgroundColor: COLORS.yellow, borderColor: COLORS.ink },
  selectionCheck: { width: 20, height: 20, imageType: "simple" },
  actionDock: { width: 390, minHeight: 92, maxHeight: 270, paddingLeft: 16, paddingRight: 16, paddingTop: 9, paddingBottom: 16, flexDirection: "column", justifyContent: "flex-end", flexShrink: 0 },
  actionRow: { width: 358, height: 60, flexDirection: "row", justifyContent: "space-between" },
  tableActionDock: { width: 390, height: 96, paddingLeft: 16, paddingRight: 16, paddingTop: 10, paddingBottom: 12, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0, backgroundColor: "#12110f", borderWidth: 2, borderColor: "#302b26" },
  tableDockHint: { ...commonText, width: 358, height: 58, lineHeight: 58, textAlign: "center", fontSize: 14, fontWeight: "bold", color: COLORS.cream },
  tableCancelButton: { width: 108, height: 58, lineHeight: 58, textAlign: "center", fontSize: 17, fontWeight: "bold", color: COLORS.cream, backgroundColor: "#12110f", borderWidth: 2, borderColor: "#5d554e", borderRadius: 7, ':active': { transform: "scale(0.97, 0.97)" } },
  tablePrimaryButton: { width: 232, height: 58, lineHeight: 58, textAlign: "center", fontSize: 20, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  tablePrimaryDisabled: { width: 232, height: 58, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#39342e", borderWidth: 2, borderColor: "#5d554e", borderRadius: 7 },
  tablePrimaryDisabledText: { ...commonText, width: 228, height: 56, lineHeight: 56, textAlign: "center", fontSize: 16, fontWeight: "bold", color: "#b8ab98" },
  button: { width: 358, height: 52, lineHeight: 52, marginBottom: 8, textAlign: "center", fontSize: 16, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.yellow, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7, ':active': { transform: "scale(0.98, 0.98)" } },
  buttonCompact: { width: 175, fontSize: 14 },
  buttonDisabled: { flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: "#39342e", borderColor: "#5d554e" },
  buttonDisabledText: { ...commonText, width: 352, height: 48, lineHeight: 48, textAlign: "center", fontSize: 15, fontWeight: "bold", color: "#b8ab98" },
  buttonCream: { backgroundColor: COLORS.cream },
  buttonCyan: { backgroundColor: COLORS.cyan, color: COLORS.ink },
  buttonRed: { backgroundColor: COLORS.red, color: COLORS.white },
  buttonInk: { backgroundColor: "#292624", color: COLORS.cream, borderColor: "#5d554e" },
  cardGrid: { width: 358, flexShrink: 0, flexDirection: "column", alignItems: "center", paddingTop: 8 },
  cardGridRow: { width: 358, height: 170, flexShrink: 0, flexDirection: "row", justifyContent: "center", alignItems: "center" },
  cardItem: { position: "relative", width: 96, height: 154, margin: 8, flexDirection: "column", alignItems: "center", backgroundColor: COLORS.cream, borderWidth: 3, borderColor: COLORS.ink, borderRadius: 7 },
  cardSelected: { backgroundColor: COLORS.cyan, borderWidth: 5, borderColor: COLORS.yellow },
  cardImage: { width: 90, height: 129, borderRadius: 4, imageType: "simple" },
  cardCheck: { position: "absolute", right: 3, top: 3, width: 28, height: 28, flexDirection: "column", alignItems: "center", justifyContent: "center", backgroundColor: COLORS.yellow, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 14 },
  cardCheckIcon: { width: 16, height: 16, imageType: "simple" },
  cardName: { width: 90, height: 25, lineHeight: 25, textAlign: "center", color: COLORS.ink, fontSize: 11, fontWeight: "bold" },
  players: { width: 358, minHeight: 95, flexDirection: "row", justifyContent: "space-around", alignItems: "center", flexShrink: 0 },
  player: { width: 68, height: 92, flexDirection: "column", alignItems: "center", justifyContent: "center", borderRadius: 6 },
  playerActive: { backgroundColor: "#2f2a25", borderWidth: 2, borderColor: COLORS.yellow },
  avatar: { width: 54, height: 54, borderRadius: 27, borderWidth: 3, borderColor: COLORS.cream },
  avatarActive: { borderColor: COLORS.yellow, borderWidth: 4 },
  playerName: { width: 66, height: 22, lineHeight: 22, textAlign: "center", color: COLORS.cream, fontSize: 10, fontWeight: "bold", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  playerStatus: { ...commonText, width: 66, height: 14, lineHeight: 14, textAlign: "center", color: "#8f8275", fontSize: 8, fontWeight: "bold", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  playerStatusActive: { color: COLORS.yellow },
  tableCanvas: { width: 358, flexGrow: 0, flexShrink: 0 },
  activityBanner: { width: 358, height: 48, paddingLeft: 10, paddingRight: 8, flexDirection: "row", alignItems: "center", justifyContent: "space-between", flexShrink: 0, backgroundColor: "#2a2725", borderWidth: 2, borderColor: "#5d554e", borderRadius: 6, ':active': { transform: "scale(0.99, 0.99)" } },
  activityBannerNeutral: { borderColor: "#766b60" },
  activityBannerAction: { borderColor: COLORS.cyan },
  activityBannerDanger: { borderColor: COLORS.red },
  activityBannerSuccess: { borderColor: COLORS.yellow },
  activityBannerFresh: { backgroundColor: "#39332d", borderWidth: 3 },
  activityBannerCopy: { width: 282, height: 40, flexDirection: "column", justifyContent: "center" },
  activityBannerTitle: { ...commonText, width: 282, height: 22, lineHeight: 22, fontSize: 12, fontWeight: "bold", color: COLORS.cream, textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityBannerDetail: { ...commonText, width: 282, height: 16, lineHeight: 16, fontSize: 9, color: "#b8ab98", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityBannerLink: { ...commonText, width: 42, height: 32, lineHeight: 32, textAlign: "center", fontSize: 10, fontWeight: "bold", color: COLORS.yellow },
  activityBackdrop: { position: "absolute", left: 0, top: 0, width: 390, height: 844, backgroundColor: "rgba(0, 0, 0, 0.72)" },
  activitySheet: { position: "absolute", left: 0, top: 422, width: 390, height: 422, paddingLeft: 16, paddingRight: 16, paddingTop: 14, flexDirection: "column", backgroundColor: "#211e1b", borderWidth: 3, borderColor: COLORS.cream, borderRadius: 7 },
  activitySheetHeader: { width: 352, height: 68, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  activitySheetCopy: { width: 250, height: 60, flexDirection: "column", justifyContent: "center" },
  activitySheetEyebrow: { ...commonText, width: 250, height: 18, lineHeight: 18, fontSize: 9, fontWeight: "bold", color: COLORS.cyan },
  activitySheetTitle: { ...commonText, width: 250, height: 36, lineHeight: 36, fontSize: 26, fontWeight: "bold", color: COLORS.cream },
  activityClose: { width: 72, height: 44, lineHeight: 42, textAlign: "center", fontSize: 12, fontWeight: "bold", color: COLORS.ink, backgroundColor: COLORS.cream, borderWidth: 2, borderColor: COLORS.ink, borderRadius: 6, ':active': { transform: "scale(0.96, 0.96)" } },
  activityPrivacy: { width: 352, height: 40, paddingLeft: 10, flexDirection: "column", justifyContent: "center", backgroundColor: "#302b26", borderRadius: 5 },
  activityPrivacyText: { ...commonText, width: 332, height: 28, lineHeight: 28, fontSize: 10, color: "#c9baa4" },
  activityTimeline: { width: 352, height: 260, paddingTop: 10, flexDirection: "column", justifyContent: "flex-end" },
  activityTimelineRow: { width: 352, height: 54, flexDirection: "row", alignItems: "center", borderWidth: 0, borderBottomWidth: 1, borderColor: "#4c443d" },
  activityTimelineMarker: { width: 10, height: 10, marginLeft: 4, marginRight: 12, borderRadius: 5, backgroundColor: "#8f8275" },
  activityTimelineMarkerNeutral: { backgroundColor: "#8f8275" },
  activityTimelineMarkerAction: { backgroundColor: COLORS.cyan },
  activityTimelineMarkerDanger: { backgroundColor: COLORS.red },
  activityTimelineMarkerSuccess: { backgroundColor: COLORS.yellow },
  activityTimelineCopy: { width: 316, height: 50, flexDirection: "column", justifyContent: "center" },
  activityTimelineTitle: { ...commonText, width: 316, height: 27, lineHeight: 27, fontSize: 13, fontWeight: "bold", color: COLORS.cream, textOverflow: "ellipsis", whiteSpace: "nowrap" },
  activityTimelineDetail: { ...commonText, width: 316, height: 18, lineHeight: 18, fontSize: 9, color: "#a99a88" },
  activityEmpty: { width: 352, height: 220, flexDirection: "column", alignItems: "center", justifyContent: "center" },
  activityEmptyTitle: { ...commonText, width: 320, height: 30, lineHeight: 30, textAlign: "center", fontSize: 16, fontWeight: "bold", color: COLORS.cream },
  activityEmptyDetail: { ...commonText, width: 320, height: 24, lineHeight: 24, textAlign: "center", fontSize: 10, color: "#a99a88" },
  error: { position: "absolute", left: 20, top: 106, width: 350, minHeight: 42, lineHeight: 20, padding: 10, textAlign: "center", color: COLORS.white, backgroundColor: COLORS.red, borderRadius: 6, borderWidth: 2, borderColor: COLORS.ink, fontSize: 11, fontWeight: "bold" },
};
